미션3_로또 게임 2등
Doolki/java-lotto pull request #10
Opened 2024-05-22 23:31 UTC by babysean

# 변경 이유
미션 3 - 로또 게임 2등 기능 개발

# 변경의 종류
- [ ] 버그 수정 (Bug fix)
- [x] 새 기능 (New feature)
- [ ] 기능 변경(Modification of the existing feature)
- [x] 리팩터링(Refactoring)

# 변경 내용
- 로또 2등을 추가합니다.
- 보너스 볼을 입력 받습니다.
- 보너스 볼은 1~45 까지의 수 이며, 앞에 당첨된 번호와는 중복될 수 없습니다.
- 2등 당첨 조건은 5개 정답, 보너스 볼 정답 입니다.
- 2등 당첨 유무에 대한 결과를 출력합니다.

# 기대 효과
- 로또 게임을 수행하고 2등에 대한 유무를 파악할 수 있습니다.

# 주요사항
- 메서드와 클래스를 잘 나누었는지 피드백이 필요합니다.

# 코드 품질
- [x] 변경 사항을 자체적으로 리뷰했습니다.
- [x] 변경 사항을 로컬에서 테스트 했습니다.
- [x] 코드의 이해를 돕기 위해 적절한 곳에 주석을 작성했습니다.
- [x] 커밋은 이해하기 쉬운 순서와 적절한 크기로 분리했습니다.

#테스트 과정
1. `LottoController.java`의 main 메서드를 실행합니다.
2. 구매 금액을 입력받고 구매 개수와 구매한 로또 번호를 출력 받습니다.
3. 지난 주 로또 당첨 번호를 입력합니다.
4. 보너스 볼을 입력합니다.
5. 구매한 로또 번호와 지난주 로또 당첨 번호를 비교하여 맞춘 개수와 수익률을 출력합니다.

2024-05-22 23:50 UTC, babysean commented
리뷰 부탁 드립니다 🙏🏼

2024-05-23 13:16 UTC, beng9re requested changes
> 메서드와 클래스를 잘 나누었는지 피드백이 필요합니다.

리뷰 완료 하였습니다. 확인 후 재요청 부탁드릴께요

2024-05-23 13:16 UTC, beng9re commented on src/main/java/lotto/domain/LastWeekLottoValidator.java
> +    public void validate(String[] number, int bonusNumber) {
보너스 넘버에 대한 유효성 체크와 로또 티켓에 대한 넘버에 대한 벨리데이션을 메소드로 분리 해보면 어떨까요?

나누게 되면 1~45에 대한 숫자 체크 벨리데이션 중복을 제거와 컨텍스트 분리의 효과가 있을꺼 같은데 한번 고민 부탁드릴께요

2024-05-23 13:16 UTC, beng9re commented on src/main/java/lotto/domain/LastWeekLottoValidator.java
> +                .allMatch(number -> number >= MIN_LOTTO_NUMBER && number <= MAX_LOTTO_NUMBER);
개인적으로 스트림안의 조건은 메서드로 분리하는 편입니다.
의도를 명확하게 할 수 있어요 
```suggestion
                .allMatch(this::isValidateNumber);


......            
      private boolean isValidateNumber(int number) {
      return number >= MIN_LOTTO_NUMBER && number <= MAX_LOTTO_NUMBER;
   }
```

2024-05-23 13:16 UTC, beng9re commented on src/main/java/lotto/domain/LottoCalculator.java
>          for (LottoTicket lottoTicket : lottoTickets) {
로또번호가 몇개가 맞았는지에 대한 책임을 `LottoTicket `으로  변경해보면 어떨까요?

2024-05-23 13:16 UTC, beng9re commented on src/main/java/lotto/domain/LottoPrize.java
> +    FIVE_AND_BONUS_MATCHES(5.1, 30_000_000),
구현했을때 고민끝에 뭔가 결정을 내린 방법 같은데 섣불리 리뷰하기 어렵군요

맞춘갯수를 소숫점으로 정의 했을때 이점이라고 하면 최적화 (성능) 관점에서 이점이 있을꺼 같은데 
한편으로는, 만약 @babysean 님 이외의 다른분이 유지보수를 하게 되면 소숫점을 보고 이게 보너스 넘버의 맞춘 갯수가 첫번째 자리임을 로직을 안 보고도 알 수 있을까요?

2024-05-23 13:16 UTC, beng9re commented on src/main/java/lotto/domain/LottoPrize.java
>      private final int prize;
그런 의미에서 해당 부분에 맞춘 갯수 필드와, 보너스 맞춘 갯수 필드를 관리하는거에 대해서 어떻게 생각하시나요?

2024-05-23 13:16 UTC, beng9re commented on src/main/java/lotto/domain/LottoTicket.java
> +    private int bonusNumber = 0;
생각해보면 저희가 로또 티켓에서는 보너스 번호를 찍고 구매하지 않을꺼 같아요!
해당 필드가 있다면 다른의미의 클래스명이 도출될꺼 같아요

2024-05-24 04:57 UTC, babysean commented on src/main/java/lotto/domain/LastWeekLottoValidator.java
> +    public void validate(String[] number, int bonusNumber) {
로또 번호 유효성 검사와 보너스 번호 유효성 검사 로직을 분리할게요 !
중복 코드를 제거할 수 있을 것 같아요 👍🏼

2024-05-24 06:19 UTC, babysean commented on src/main/java/lotto/domain/LastWeekLottoValidator.java
> +                .allMatch(number -> number >= MIN_LOTTO_NUMBER && number <= MAX_LOTTO_NUMBER);
```
public void winningNumbersValidation(List<Integer> numbers) {
    // 숫자 개수 검사
    this.checkCorrectLottoFormat(numbers);

    // 범위 검사
    numbers.forEach(this::checkCorrectRange);

    // 중복 검사
    this.checkUniqueNumber(numbers);
}
```

이렇게 변경해보았어요 !

2024-05-24 07:52 UTC, babysean commented on src/main/java/lotto/domain/LottoPrize.java
> +    FIVE_AND_BONUS_MATCHES(5.1, 30_000_000),
코멘트 주신거 보고 생각해보니
저만 알아볼 수 있는 상당히 이기적인 소스였네요 .. 😢

2024-05-25 02:49 UTC, babysean commented on src/main/java/lotto/domain/LottoCalculator.java
>          for (LottoTicket lottoTicket : lottoTickets) {
로또 당첨 번호의 개수를 도출하는 메서드를 `LottoTicket` 에 작성했어요 !
LottoCalculator는 오로지 '계산'을 하는 클래스로 두어볼게요 !

2024-05-25 03:40 UTC, babysean commented on src/main/java/lotto/domain/LottoTicket.java
> +    private int bonusNumber = 0;
가변필드는 도메인 객체에서 제거 해볼게요 !

2024-05-25 09:17 UTC, babysean commented on src/main/java/lotto/domain/LottoPrize.java
>      private final int prize;
보너스 맞춘 여부도 enum 으로 관리할게요 !

2024-05-25 09:21 UTC, babysean commented
리뷰 부탁 드립니다 🙏🏼 

**_로또 결과 확인_** 로직 위주로 리뷰 부탁드려요 (`LottoService.calculate()`)

2024-05-26 07:44 UTC, beng9re requested changes
> 로또 결과 확인 로직 

리뷰 완료 했습니다. 한번 확인 해보시고 재요청 주세요~

2024-05-26 07:44 UTC, beng9re commented on src/main/java/lotto/domain/LottoTicket.java
> +    public LottoResult win(LottoTicket winningNumber, int bonusNumber) {
LottoPrize를 만들었으니 LottPrize로 반환해보는게 어떨까요?

2024-05-26 07:44 UTC, beng9re commented on src/main/java/lotto/domain/LottoTicket.java
> +    /** 로또 번호 */
피드백 반영 좋습니다

2024-05-26 07:44 UTC, beng9re commented on src/main/java/lotto/domain/LottoPrize.java
> +    private final boolean bonusNumber;
사소한 부분이긴 한대 boolean이니 그에 맞는 변수를 선언해보면 좋을꺼 같아요

2024-05-26 07:44 UTC, beng9re commented on src/main/java/lotto/service/LottoService.java
>          LastWeekLottoValidator validator = new LastWeekLottoValidator();
LastWeekLottoValidator를 한번만 생성하도록 한번 변경해보세용

2024-05-27 05:49 UTC, babysean commented on src/main/java/lotto/domain/LottoPrize.java
> +    private final boolean bonusNumber;
isWonBonusNumber 으로 변경 할게요

2024-05-27 06:02 UTC, babysean commented on src/main/java/lotto/service/LottoService.java
>          LastWeekLottoValidator validator = new LastWeekLottoValidator();
팩토리 패턴 사용해서 생성하도록 개선할게요 !

2024-05-28 01:04 UTC, babysean commented on src/main/java/lotto/domain/LottoTicket.java
> +    public LottoResult win(LottoTicket winningNumber, int bonusNumber) {
로또 결과를 LottoPrize 로 관리하도록 수정했어요 !

2024-05-28 01:04 UTC, babysean commented
리뷰 부탁 드립니다 🙏🏼 🙏🏼

2024-05-31 07:28 UTC, beng9re requested changes
반영할부분 잘 반영해주셨어요.
한번만 더 확인 후 재요청  부탁 드릴께요

지난 LottoResult 클래스를 LottoPrize로 대체하면서 어떠한 느낌을 받았는지도 공유해주시면 좋을꺼 같아요 :)

2024-05-31 07:28 UTC, beng9re commented on src/main/java/lotto/domain/LottoCalculator.java
> +    public int getCountOfWin(List<LottoPrize> prizes, int checkedCount, boolean isWonBonusNumber) {
해당 부분의 메서드의 비교하는 파라미터를 List<LottoPrize> prizes, LottoPrize checkPrize 로 받으면 효과가 더좋을꺼 같은데 한번 적용해보시겠어요?

2024-05-31 07:28 UTC, beng9re commented on src/main/java/lotto/domain/LottoResult.java
오호 LottoPrize를 사용하면서 Result또한 제거 되었군요 좋습니다

2024-05-31 07:28 UTC, beng9re commented on src/main/java/lotto/domain/LottoPrize.java
> -    THREE_AND_BONUS_MATCHES(3, true, 5_000),
안쓰는 부분 정리 👍

2024-05-31 07:28 UTC, beng9re commented on src/main/java/lotto/service/LottoService.java
> +        this.removeNullList(winningResult);
this 키워드 좋습니다

2024-05-31 07:28 UTC, beng9re commented on src/main/java/lotto/service/LottoService.java
> +    LastWeekLottoValidator validator;
흠.. 해당 접근제한자가 디폴트인 이유가 있을까요?

2024-06-03 07:29 UTC, babysean commented on src/main/java/lotto/service/LottoService.java
> +        this.removeNullList(winningResult);
`this` 키워드를 쓰는 것이 명확히 어떤 것을 가리키는지 알기 쉽기 때문이라고 알고 있는데, 이 이유가 맞을까요 ~ ?

2024-06-03 07:53 UTC, babysean commented on src/main/java/lotto/service/LottoService.java
> +    LastWeekLottoValidator validator;
아 ! 이유 없습니다 ! 제가 놓친 부분이에요

2024-06-04 23:27 UTC, babysean commented on src/main/java/lotto/domain/LottoCalculator.java
> +    public int getCountOfWin(List<LottoPrize> prizes, int checkedCount, boolean isWonBonusNumber) {
파라미터를 `public int getCountOfWin(List<LottoPrize> prizes, LottoPrize checkedPrize)` 변경했습니다 !

2024-06-04 23:33 UTC, babysean commented
리뷰 부탁 드립니다 🙏🏼

2024-06-05 04:01 UTC, beng9re commented on src/main/java/lotto/service/LottoService.java
> +        this.removeNullList(winningResult);
개인적으로는 명확해서 좋더라구요!

2024-06-12 15:36 UTC, beng9re approved these changes
피드백 잘 반영해주셨습니다 ~!

남길 코멘트 남겨드렸고 다음 단계는 메신저를 통해 안내드리도록 하겠습니다.

2024-06-12 15:36 UTC, beng9re commented on src/main/java/lotto/service/LottoService.java
> +    private final LastWeekLottoValidator validator;
이제 외부에서 접근이 안되겠네요 좋습니다 👍

2024-06-12 15:36 UTC, beng9re commented on src/main/java/lotto/domain/LottoCalculator.java
> +                .filter(prize -> LottoPrize.isMatched(prize, checkedPrize.getMatches(), checkedPrize.getIsWonBonusNumber()))
```Suggestion
filter(prize -> prize ==  checkedPrize)
```
enum으로 바꾼 만큼 다음과 같이 비교 해볼수도 있을꺼 같아요

2024-06-12 15:36 UTC, merged