미션3 로또게임2등
Doolki/java-lotto pull request #11
Opened 2024-05-24 14:34 UTC by Lee-YuGyeong

# 변경 이유
- 보너스 번호를 추가합니다.

# 변경의 종류
- [ ] 버그 수정 (Bug fix)
- [ ] 새 기능 (New feature)
- [x] 기능 변경(Modification of the existing feature)
- [ ] 리팩터링(Refactoring)

# 변경 내용
1. 보너스 번호 추가

# 기대 효과

# 주요사항
- 

# 코드 품질
- [x] 변경 사항을 자체적으로 리뷰했습니다.
- [x] 변경 사항을 로컬에서 테스트 했습니다.
- [x] 코드의 이해를 돕기 위해 적절한 곳에 주석을 작성했습니다.
- [x] 커밋은 이해하기 쉬운 순서와 적절한 크기로 분리했습니다.

2024-05-26 04:58 UTC, beng9re commented on src/main/java/exam2/lotto/LottoNumber.java
> +public class LottoNumber implements Comparable<LottoNumber> {
소팅을 위한 Comparable 좋은데요 👍

2024-05-26 06:02 UTC, beng9re requested changes
전반적으로 코드 잘 작성해주셨습니다.

LottoNumber와 같은 원자값을 추출해준부분이 인상깊었습니다! 
피드백 남겨 두었으니 확인후 재요청 부탁드릴께요

2024-05-26 06:02 UTC, beng9re commented on src/main/java/exam2/lotto/LottoNumber.java
> +public class LottoNumber implements Comparable<LottoNumber> {
로또번호에 대한 원시값을 포장하면서 로또번호만 관리 할 수도 있겠네요 좋습니다 💯

2024-05-26 06:02 UTC, beng9re commented on src/main/java/exam2/lotto/LottoNumber.java
> +        this.number = checkValidRange(number);
```suggestion
        this(checkValidRange(number));
```
다음과 같이 바꾸면 해당 생성자를 부 생성자로 사용함으로써 한군데에서 관리를 할 수 있을꺼 같아요!

2024-05-26 06:02 UTC, beng9re commented on src/main/java/exam2/lotto/LottoNumber.java
> +        return Integer.parseInt(inputNumber.trim());
```suggestion
        try  {
             return Integer.parseInt(inputNumber.trim());
        } catch (NumberFormatException e) {
            throw new NumberFormatException("숫자가 아닌 값을 입력할 수 없습니다");
        }
```
생성자를 한쪽에서 관리하면 이렇게 제거 할 수도 있을꺼 같아요. 
그러면 해당 메서드의 이름은 문자인지 아닌지 체크를 하게 될꺼 같네요.

2024-05-26 06:02 UTC, beng9re commented on src/main/java/exam2/lotto/LottoNumber.java
> +            throw new IllegalArgumentException("1 ~ 45 사이 값을 입력 해주세요");
이제 로또 넘버라는 객체가 나왔으니 어울리는 익셉센 메시지를 작성하는것도 좋아보여요 (재활용이 가능하겠끔) 
1 ~ 45 사이 값을 입력 해주세요 -> 로또번호는 1 ~ 45 사이 값 이어야 합니다

2024-05-26 06:02 UTC, beng9re commented on src/main/java/exam2/lotto/LottoNumber.java
> +    private int number;
해당 부분은 값이 확실하게 안바뀌는 영역으로 final을 추가해보면 좋을꺼 같아요!

2024-05-26 06:02 UTC, beng9re commented on src/main/java/exam2/lotto/LottoNumber.java
> +            throw new IllegalArgumentException("1 ~ 45 사이 값을 입력 해주세요");
기존의 LottoNumbers 클래스에서 LottoNumber를 추출하면서 벨리데이션 로직이 이쪽으로 넘어왔군요! 
이제는 로또번호에 대한건 로또번호 클래스만 보면 되겠네요! 좋습니다

2024-05-26 06:02 UTC, beng9re commented on src/main/java/exam2/lotto/LottoPrize.java
> +    public int getRank() {
안쓰는 getter는 지워주는게 좋습니다

2024-05-26 06:02 UTC, beng9re commented on src/main/java/exam2/lotto/WinningNumber.java
>      public WinningNumber(String lottoStr) {
bonusNumber를 관리하는 만큼 생성할때부터 bonusNumber를 만들어도 좋을꺼 같아요

2024-05-26 06:02 UTC, beng9re commented on src/test/java/exam2/lotto/LottoNumberRowTest.java
>  @DisplayName("로또 계산기")
이제 봤네요 로또계산기에 대한 테스트는 아니 여서 변경해보면 좋을꺼 같아요

2024-05-26 06:02 UTC, beng9re commented on src/test/java/exam2/lotto/WinningNumberTest.java
> +}
파일끝에 공백이 없어요 ㅜ

2024-05-26 06:02 UTC, beng9re commented on src/main/java/exam2/lotto/LottoPrize.java
> +    ZERO(8, 0, 0, 0),
ENUM의 장점은 의미를 문자열로 남길수 있다는 장점이 있는데요 
ZERO ONE 보다는 좀더 명확한 의미를 선언해보면 좋을꺼 같아요 

로또보상클래스이니 어울리는 단어를 선택해보면 좋을꺼 같아요

2024-06-01 16:08 UTC, Lee-YuGyeong commented on src/main/java/exam2/lotto/LottoNumber.java
> +        this.number = checkValidRange(number);
수정하였습니다!!

2024-06-01 16:10 UTC, Lee-YuGyeong reviewed
수정해서 다시 올립니다~~

2024-06-01 16:11 UTC, Lee-YuGyeong commented on src/main/java/exam2/lotto/LottoNumber.java
> +        return Integer.parseInt(inputNumber.trim());
수정했습니다! 저렇게 수정하니까 훨씬 코드가 간결해져서 좋네요 ^ㅡ^

2024-06-02 13:34 UTC, beng9re commented on src/main/java/exam2/lotto/LottoPrize.java
> +    SECOND(3, 5, 0, 1_500_000),
흠... 이부분이 정말 2등일까요?

2024-06-02 13:49 UTC, beng9re requested changes
지난번 리뷰때 마저 체크하지 못 한부분 리뷰 드렸어요 한번 확인 부탁드릴께요

2024-06-02 13:49 UTC, beng9re commented on src/main/java/exam2/lotto/PurchaseTicket.java
> +        if (winning.getBonusNumber() == null) {
WinningNumber에 보너스넘버가 있는지 없는지를 체크하는게 PurchaseTiket의 책임이 맞을까요?

2024-06-02 13:49 UTC, beng9re commented on src/main/java/exam2/lotto/PurchaseTicket.java
> +            int count = (int) lottoNumberRow.getNumberList().stream()
해당부분의 책임을 WinningNumber에게 위임 해보는게 어떨까요?

2024-06-16 06:05 UTC, Lee-YuGyeong commented on src/main/java/exam2/lotto/PurchaseTicket.java
> +            int count = (int) lottoNumberRow.getNumberList().stream()
당첨번호 세는 기능을 WinningNumber 위임하면 수익 비율 계산하는것도 WinningNumber 로 넘겨야할까요 ??

2024-06-16 06:06 UTC, Lee-YuGyeong reviewed
변경했습니다!!!

2024-06-18 13:48 UTC, beng9re reviewed
> 당첨번호 세는 기능을 WinningNumber 위임하면 수익 비율 계산하는것도 WinningNumber 로 넘겨야할까요 ??

제가 의도한건 갯수만 새고 WinningNumber가 LottoPrize만 반환 하는 형태이고 수익 비교는 그이후에 적당한 객체에 넣어주면 좋을꺼 같아요 .
아니면 Map<LottoPrize, count> 와 같은 자료구조를 리턴해주는 형태가 좋지 않을까 싶어요 

현재 WinningNumber.calculateMatchCount 를 수행하면 
PurchaseTicket 내부의 Map<LottoPrize, count>를 직접꺼내서 데이터가 추가 되는것으로 이해를 했는데 이렇게 되면 만든사람은 잘 이해하고 딱 한번만 호출하고 끝나겠지만,

다른 사람이 두번 호출하거나 악의적으로 해당 맵에 데이터를 추가하게 되어 예상치 못한 사이드 이펙트가 발생 될 수 있어요. 🥲

`내부의 상태는 해당 객체만이 바꿀수 있다`라는 사실을 기억해주셨으면 해요

2024-06-18 13:48 UTC, beng9re commented on src/main/java/exam2/lotto/WinningNumber.java
> +        if (bonusNumber == null) {
bonusNumber는 null이 될수 없지 않을까요?

2024-06-18 13:48 UTC, beng9re commented on src/main/java/exam2/lotto/WinningNumber.java
> +            int count = (int) lottoNumberRow.getNumberList().stream()
lottoNumberRow와 winningNumberRow는 같은 타입이니까 LottoNumberRow 해당 클래스에서 갯수만 세는 함수를 넣는다면 
결합도는 떨어지고 응집도가 높아질꺼 같아요.

`lottoNumberRow.matchCount(winningNumberRow)` 등과 같이요

2024-06-18 13:48 UTC, beng9re commented on src/main/java/exam2/lotto/WinningNumber.java
> +            int bonus = (int) lottoNumberRow.getNumberList().stream()
이 부분도 LottoNumberRow에게 getter를 통해 직접 탐색하는게 아닌 물어본다면 좋을꺼 같아요

2024-06-18 13:50 UTC, beng9re commented on src/main/java/exam2/lotto/WinningNumber.java
> +                .put(lottoPrize, purchaseTicket.getMatchCount().get(lottoPrize) + 1);
이 부분이 다른 친구의 상태를 직접 바꾸고 있어요

2024-07-01 13:37 UTC, Lee-YuGyeong reviewed
로또번호 일치하는 개수 계산하는 부분과 실제로 업데이트하는 부분 나누었습니다!!!

2024-07-02 14:40 UTC, beng9re requested changes
https://brunch.co.kr/@springboot/292
Given when then 에 맞추어서 테스트 코드를 작성해주시면 좀더 가독성 있는 테스트 코드를 작성 할 수 있어요! 

그리고 테스트 준비 대상인 데이터에 대해 재활용을 위해서 Test-Fixture를 적용해보시면 좋을꺼 같아요 

한번더 재요청 부탁드려요

2024-07-02 14:40 UTC, beng9re commented on src/main/java/exam2/lotto/LottoNumberRow.java
> +    public int matchCount(LottoNumberRow lottoNumberRow) {
이 부분 테스트가 추가되지 않은 이유가 있을까요?

2024-07-02 14:40 UTC, beng9re commented on src/main/java/exam2/lotto/PurchaseTicket.java
> +    public void updateMatchCount(WinningNumber winningNumber) {
피드백 반영 좋습니다.

2024-07-02 14:40 UTC, beng9re commented on src/main/java/exam2/lotto/WinningNumber.java
>      public LottoNumberRow getLottoNumberRow() {
뭔가 getter를 꼭 만드는 습관이 있는 듯 해요.

해당 메서드는 쓰지 않는 부분이 있음에도 구현이 되어 있군요.
쓰지 않는 메서드에 대해서는 구현하지 않는게 좋습니다. 
그 이유는 규모가 커짐에 따라 변경사항이 많아지면 구현한 대상에 대해서도 유지보수 해야하나? 라는 인지부조화가 걸리기도 하고 
이걸 지워도 되냐? 에 대한 고민거리도 남길수도 있을꺼 같아요

2024-07-08 05:03 UTC, Lee-YuGyeong commented on src/main/java/exam2/lotto/LottoNumberRow.java
> +    public int matchCount(LottoNumberRow lottoNumberRow) {
까먹었어요 흑흑 ㅜ

2024-07-08 05:08 UTC, Lee-YuGyeong reviewed
테스트 코드 추가하고 사용하지 않는 getter 삭제하여 다시 올립니다 !

2024-07-13 04:54 UTC, beng9re approved these changes

2024-07-13 04:54 UTC, beng9re commented on src/test/java/exam2/lotto/LottoNumberRowTest.java
> +        winningNumberList.add(16);
자바 버전이 될지 모르겠지면 
 List<Integer> winningNumberList = List.of(1,2,14,15,16) 과 같이 작성해도 되지 않나여?

2024-07-13 04:54 UTC, beng9re commented on src/test/java/exam2/lotto/LottoNumberRowTest.java
> +        numberList.add(1);
테스트 준비 코드가 많다면 
@BeforeEach? 활용해볼수도 있을꺼 같네요

https://velog.io/@ak2j38/Junit-BeforeEach-BeforeAll-AfterEach-AfterAll%EB%A5%BC-%EC%95%8C%EC%95%84%EB%B3%B4%EC%9E%90

2024-07-13 04:54 UTC, beng9re commented on src/main/java/exam2/lotto/WinningNumber.java
> -    public LottoNumberRow getLottoNumberRow() {
정리 좋습니다 👍

2024-07-13 04:55 UTC, merged

2024-07-13 04:55 UTC, beng9re commented
머지 했습니다 다음단계 진행해주세여

2024-07-15 00:48 UTC, Lee-YuGyeong commented on src/test/java/exam2/lotto/LottoNumberRowTest.java
> +        winningNumberList.add(16);
버전이 안되네요 ㅜ

2024-07-15 13:27 UTC, beng9re commented on src/test/java/exam2/lotto/LottoNumberRowTest.java
> +        winningNumberList.add(16);
9부터 지원인데여?
![image](https://github.com/user-attachments/assets/7e7d2c6d-4be3-40c3-8c53-1e04847a6cb4)


![image](https://github.com/user-attachments/assets/d6dad4a6-d236-44c0-8ebd-72f6a1d0d142)