feat : 로또게임 수동
Doolki/java-lotto pull request #13
Opened 2024-08-25 10:31 UTC by Lee-YuGyeong

feat : 로또게임 수동
- 수동 기능 추가

2024-08-25 10:33 UTC, Lee-YuGyeong reviewed
수동 버전 추가 완료했습니닷...! .......

2024-08-27 10:36 UTC, beng9re requested changes
코멘트 남겨두었습니다! 

해당 요구사항에 `예외 처리를 통해 에러가 발생하지 않도록 한다.` 라는 요구사항이 있는데요 
지금 현재 잘못된값이 들어오면 그대로 프로그램이 종료가 되요 이부분을 재요청을 받는식으로 수정하면 좋을꺼 같습니다! 

그리고 Main 메서드에서의 책임이 너무 많은데요 LottoService를 만들었으니 
핵심 도메인의 생성 (LottoNumber, PurchaseTiket)등 을 LottoSerivce에서 만들고 활용하는 형태로 리팩토링 부탁드립니다

2024-08-27 10:36 UTC, beng9re commented on build.gradle
> +sourceCompatibility = JavaVersion.VERSION_16
왜 하필 java 16인가여..

2024-08-27 10:36 UTC, beng9re commented on src/main/java/exam2/lotto/PurchaseTicket.java
> +    public static PurchaseTicket createAutoLottoNumber(int price,
메서드 명이 createAutoLottoNumber인데 실제로는 수동로또와, 자동로또 둘다 생성하네요
메서드 명을 buyLottoTiket으로 지정 하는것이 어떨까요?

2024-08-27 10:36 UTC, beng9re commented on src/main/java/exam2/Main.java
> +        resultView.purchaseManualCount();
사용자에 입력에 대한 안내군요 호출 해보니 inputView에서 생성하는게 어울릴꺼 같아요

2024-08-28 13:50 UTC, Lee-YuGyeong commented on src/main/java/exam2/lotto/PurchaseTicket.java
> +    public static PurchaseTicket createAutoLottoNumber(int price,
넵~!

2025-03-23 10:35 UTC, closed without merging