feat: 명시된 구분자를 이용하여 문자열을 자르고 그 합을 구하는 함수 개발
Doolki/java-lotto pull request #3
Opened 2024-04-22 01:59 UTC by babysean

- 파라미터에서 "//" 과 "\n" 사이에 명시된 구분자 추출
 - 구분자를 이용하여 문자열 split
 - split된 string 배열에 음수가 있는지 확인
 - 음수가 있다면 exception 발생, 아니면 총 합을 반환

2024-04-24 13:48 UTC, beng9re commented on src/main/java/StringCalculator.java
> +public class StringCalculator {
문자열을 계산하는 StringCalculator라는 클래스로 추출 한 점 좋습니다.  💯

2024-04-24 13:50 UTC, beng9re commented on src/main/java/StringCalculator.java
> +    private final String stringNumbers;
지금 stringNumbers, splitNumbers의 변수로 현재 상태를 관리하게 되었는데 
상태를 관리하게 된 이유가 있을까요?

2024-04-24 13:54 UTC, beng9re commented on src/main/java/StringCalculator.java
> +    // 문자열을 명시된 구분자에 맞게 split 하여 변수에 저장합니다.
보기좋은 주석 좋습니다. 
개인적으로 해당 메서드를 설명하는 주석은 javaDoc 주석을 활요하는것을 선호하는데요.
그 이유는 IDE에 도움을 받아 설명이 나오기 때문이에요 
```java 
/**
* 문자열을 명시된 구분자에 맞게 split 하여 변수에 저장합니다.
*/
```
![image](https://github.com/Doolki/java-lotto/assets/26699273/cf373b59-6377-41b7-9ec9-39397347fce8)

2024-04-24 13:54 UTC, beng9re commented on src/main/java/StringCalculator.java
> +}
파일의 끝에는 공백을 추가하는 POSIX 룰이 있어요!
https://dongminkim94.tistory.com/72 한번 참고 부탁드릴께요

2024-04-24 13:56 UTC, beng9re commented on src/main/java/StringCalculator.java
> +                    throw new NumberFormatException("Invalid format: 음수가 포함 되어있습니다.");
NumberFormatException클래스면 NumberFomat에 관련된 익셉션이라고 생각이 되는데요 
음수 같은 경우에는 NumberFormat에는 부합이 된다고 생각되고 다른 종류의 익셉션이 어울린다고 생각하는데 어떻게 생각하시나요?

2024-04-24 14:07 UTC, beng9re commented on src/test/java/StringCalculatorTest.java
> +    void 명시된_구분자로_문자열을_자르고_그_값들의_합을_반환합니다() {
테스트코드에 로직이 담겨있어요!

로직을 담게 되면 해당 로직에 대한 검증은 어떻게 테스트할 수 있을까요?
해당 테스트 내부의 로직이 실패하면 불안정한 테스트를 만든다고 생각이 되요

> 참조 
https://learn.microsoft.com/ko-kr/dotnet/core/testing/unit-testing-best-practices#avoid-logic-in-tests

2024-04-24 14:10 UTC, beng9re commented on src/main/java/StringCalculator.java
> +        String customDelimiter = stringNumbers.substring(2, delimiterEndIndex);
만약에 구분하는 문자열이 만약에 여러 글자라면? 
해당 부분은 정상적으로 수행되지 않을거 같아요......  🥲

2024-04-24 14:11 UTC, beng9re commented on src/main/java/StringCalculator.java
> +        if (!stringNumbers.startsWith("//")) {
만약에 stringNumbers가 null이라면 해당 부분은 예외가 발생할꺼 같습니다!
이 부분에 대한 테스트를 넣어준다면? 이를 방지 할 수 있겠죠?

2024-04-24 14:15 UTC, beng9re requested changes
기존의 코드를 작성했던 부분과 많이 상이할수도 있는데 
전반적으로 로직 잘 작성해주셨습니다 👍

한번 코멘트 확인해보시구 재 요청 부탁 드릴께요!
처음이라 핑퐁하는 구간이 많을텐데 지치지마시고 잘 따라와 주시면 조금더 성장하지 않을까? 합니다!

코멘트상 이해가 되지 않는 부분은 코멘트 해주셔도 좋고 메신저 해주셔도 좋습니다! 
언제든지 요청주세요

(성공하는 테스트만 작성되었는데 실패를 검증하는 테스트도 중요합니다!)

2024-04-26 05:25 UTC, babysean commented on src/main/java/StringCalculator.java
> +    private final String stringNumbers;
절차상 필요없는 변수인 "stringNumbers"가 사용되고 있었습니다

제거하고 소스 개선 해보겠습니다 👍🏼

2024-04-26 05:27 UTC, babysean commented on src/main/java/StringCalculator.java
> +    // 문자열을 명시된 구분자에 맞게 split 하여 변수에 저장합니다.
메서드 설명 부분에는 JavaDoc 주석을 사용하겠습니다 !
(원래 JavaDoc 주석 사용했었는데 ㅠㅠ)

2024-04-26 06:06 UTC, babysean commented on src/main/java/StringCalculator.java
> +                    throw new NumberFormatException("Invalid format: 음수가 포함 되어있습니다.");
IllegalArgumentException이 적절하다고 생각합니다

2024-04-27 03:44 UTC, beng9re commented on src/main/java/StringCalculator.java
>      private void checkFormat() {
피드백 반영 👍

2024-04-27 03:44 UTC, beng9re commented on src/main/java/StringCalculator.java
> +            throw new IllegalArgumentException("Invalid format: 구분자 형식이 맞지 않습니다.");
명확한 익셉션 좋습니다

2024-04-27 12:49 UTC, babysean commented on src/main/java/StringCalculator.java
> +        String customDelimiter = stringNumbers.substring(2, delimiterEndIndex);
<img width="601" alt="image" src="https://github.com/Doolki/java-lotto/assets/26477789/a7cea41f-9d75-401e-983c-23e2e152840b">

숫자를 구분하는 구분자가 `::` 일 경우, 정상적으로 실행됩니다.

<img width="597" alt="image" src="https://github.com/Doolki/java-lotto/assets/26477789/da22179b-6fae-4137-a390-73bb45e63146">

주석을 한 번 달아봤는데 제가 잘못 이해했을까요 ?

2024-04-27 13:29 UTC, beng9re commented on src/main/java/StringCalculator.java
> +        String customDelimiter = stringNumbers.substring(2, delimiterEndIndex);
앗 제가 잘못봤네요 ㅎㅎ;

관련 부분을 테스트코드에 추가하면 좋을꺼 같아요!

2024-04-27 14:08 UTC, babysean commented on src/main/java/StringCalculator.java
> +        String customDelimiter = stringNumbers.substring(2, delimiterEndIndex);
😢

2024-04-27 14:08 UTC, closed without merging

2024-04-27 14:08 UTC, babysean commented
다시 PR 전달하겠습니다 ㅎㅎ