미션1_학습테스트&문자열계산기
Doolki/java-lotto pull request #5
Opened 2024-04-25 15:59 UTC by Lee-YuGyeong

feat: 미션1 문자열 계산기 만들기

**변경내용**
test 코드 추가함
문자열 계산기 service 로직 따로 구현
Exception 클래스 따로 구현

**기대효과**
문자열 계산기 기능 구현

**궁금한점**
Calculator.strSplit(String str)에서 str null 체크 하는 부분은 Exception 클래스로 따로 빼야할까요?

2024-04-26 02:06 UTC, beng9re requested changes
피드백 확인 해보시고 다시 한번 요청 부탁드릴께요!

2024-04-26 02:06 UTC, beng9re commented on src/main/java/Exam1/Calculator.java
> +        Pattern pattern = Pattern.compile(STR_SPLIT_PATTERN);
![image](https://github.com/Doolki/java-lotto/assets/26699273/b9908a52-4cda-49ef-9a95-7b7e6c39371e)

Pattern 클래스에서 정규식을 컴파일을 진행할때 객체 생성 비용이 비싼편이라 컴파일을 해놓고 사용하는것을 권장하고 있어요 
해당 구문을 상수로 빼면 최적화가 가능할꺼 같습니다.

```java
private static final Pattern pattern = Pattern.compile(STR_SPLIT_PATTERN); 
```

2024-04-26 02:06 UTC, beng9re commented on src/main/java/Exam1/CalculatorService.java
> +public class CalculatorService {
문자열 계산기에 비지니스 로직 처리를 위한 서비스 클래스 좋습니다! 

벨리데이션 로직을 나누는 관점에서는 분리가 좋을꺼 같구요.
합치게 된다면  별도 서비스 클래스 보다는 Calculator에 넣는게 적절해 보입니다!

이 부분은 선택사항이라 생각해보시구 반영해보세요

2024-04-26 02:06 UTC, beng9re commented on src/main/java/Exam1/CalculatorService.java
> +        Calculator calculator = new Calculator();
정적 스태틱 메서드로 사용할 수도 있었는데 객체를 만들어서 사용하셨군요! 좋습니다 👍 

아실수도 있지만 해당 부분에 DI를 활용하보면 좋을꺼 같아요 
해당 메서드에서 Calculator 해당 클래스를 생성하게 되면 호출할때마다 객체가 생길꺼 같아요!
그리고 만약에 `Calculator`의 생성자를 변경하게 되면 필연적으로 해당 메서드는 변경이 될꺼 같아서 강한 결합 상태처럼 보여서요!

이부분에 대해서는 어떻게 생각하시나요?

2024-04-26 02:06 UTC, beng9re commented on src/main/java/Exam1/Exception.java
> +public class Exception {
Exception이라는 클래스명을 보면 익셉션이 떠오르게 되는데 안에 내부 로직은 계산기 클래스에서 메서드 내부에서 벨리데이션(유효성)을 검사하는 클래스로 보이네요 CalculatorValidate와 같은 명칭이 적절해보입니다. 

논의 했던것 처럼 합쳐도 좋고 나누셔도 좋을꺼 같아요 
익셉션에 대한 참고 링크도 공유 드립니다.
https://beststar-1.tistory.com/19

2024-04-26 02:06 UTC, beng9re commented on src/main/java/Exam1/Exception.java
> +        if (num <0) {
위에는 `if (str == null)` 작성해주셧고 여기 코드는 `if (num <0)`과 같이 작성해주셨네요 통일 시키는게 좋아보입니다.
코드 자동정렬 (옵션 + 커멘드 L)을 사용해주시면 편리하게 가능합니다.

2024-04-26 02:06 UTC, beng9re commented on src/test/java/Exam1/CalculatorTest.java
> +class CalculatorTest {
테스트코드 잘 작성 해주셨습니다 💯

2024-04-26 02:06 UTC, beng9re commented on src/test/java/Exam1/CalculatorTest.java
> +    @DisplayName("입력 문자열 null 체크")
디스플레이 네임에는 
`입력하는 문자열이 null이면 예외가 발생한다`와 같이 명확하게 작성하는게  좋습니다

2024-04-26 02:06 UTC, beng9re commented on src/test/java/Exam1/CalculatorTest.java
> +                .hasMessage("문자는 빈값이 될 수 없습니다.");
```suggestion
        assertThatNullPointerException()
                .isThrownBy(() -> calculator.strSplit(input))
                .hasMessage("문자는 빈값이 될 수 없습니다.");
```
다음과 같이 작성해볼수도 있습니다~

2024-04-26 02:06 UTC, beng9re commented on src/test/java/Exam1/ExceptionTest.java
> +        String[] input = {"1","-2","0"};
0도 포함해서 확인 해주셧군요 경계값 테스트 좋습니다

2024-04-26 02:06 UTC, beng9re commented on src/main/java/Exam1/Exception.java
> +            throw new RuntimeException("음수 값 전달 에러");
음수값 전달 에러 보다는 명확하게 작성하면 좋을꺼 같아요 
`문자열 계산기에서는 음수가 전달되면 안됩니다.` 등과 같이요

2024-04-26 14:43 UTC, Lee-YuGyeong commented on src/test/java/Exam1/CalculatorTest.java
> +                .hasMessage("문자는 빈값이 될 수 없습니다.");
좋은 코멘트 감사합니다!
assertThatNullPointerException을 사용할때는 hasMessage 대신 withMessage를 사용한다고 하네요!

2024-04-27 03:45 UTC, beng9re commented on src/test/java/Exam1/CalculatorTest.java
> +                .hasMessage("문자는 빈값이 될 수 없습니다.");
앗 그렇네요! 감사합니다!

2024-04-27 03:47 UTC, beng9re commented on src/main/java/Exam1/CalculatorService.java
> +        Calculator calculator = new Calculator();
DI를 활용했지만 여전히 객체를 생성해서 사용하고 있어요!

2024-04-27 03:47 UTC, beng9re commented on src/main/java/Exam1/CalculatorService.java
> +        CalculatorValidate calculatorValidate = new CalculatorValidate();
CalculatorValidate또한 DI패턴으로 변경해줄 수 있을꺼 같습니다!

2024-04-27 03:48 UTC, beng9re commented on src/main/java/Exam1/CalculatorValidate.java
> +            throw new NumberFormatException("숫자가 아닌 요소는 전달이 불가능 합니다");
피드백 반영 좋습니다 👍

2024-04-27 03:53 UTC, beng9re approved these changes
피드백 잘 반영해주었습니다! 
이번 단계는 이만 머지 하겠습니다.
다음 단계 미션으로 넘어가주세요!

코멘트의 변경사항은 다음단계에 포함해서 PR요청 부탁드립니다 🙏

2024-04-27 03:53 UTC, beng9re commented on src/test/java/Exam1/CalculatorTest.java
> +    @DisplayName("입력하는 문자열이 null이면 예외가 발생한다")
좀 더 명확해졌군요 좋습니다 👍

2024-04-27 03:54 UTC, merged