미션2_로또 게임 자동
Doolki/java-lotto pull request #7
Opened 2024-04-28 15:47 UTC by Lee-YuGyeong

# 변경 이유
로또 게임을 생성한다.

# 변경의 종류
- [ ] 버그 수정 (Bug fix)
- [x] 새 기능 (New feature)
- [ ] 기능 변경(Modification of the existing feature)
- [ ] 리팩터링(Refactoring)

# 변경 내용
1. 로또 게임 기능 구현
2. 로또 게임 테스트 코드 구현

# 기대 효과

# 주요사항

# 코드 품질
- [x] 변경 사항을 자체적으로 리뷰했습니다.
- [x] 변경 사항을 로컬에서 테스트 했습니다.
- [x] 코드의 이해를 돕기 위해 적절한 곳에 주석을 작성했습니다.
- [x] 커밋은 이해하기 쉬운 순서와 적절한 크기로 분리했습니다.

2024-04-29 07:58 UTC, beng9re requested changes
미션 2단계 하시느라 고생 많으셨습니다!

Lotto의 책임이 너무 많은거 같아요! 클래스도 단일책임원칙을 생각해보시면서 이게 한가지의 책임을 가지는지 한번 생각해보시는게 좋을꺼 같습니다!

생각할 코멘트 거리 남겨두었으니 수정후 재요청 (PR 문서에 재요청합니다)라고 부탁드립니다.

2024-04-29 07:58 UTC, beng9re commented on src/main/java/Exam2/LottoDTO.java
> +public class LottoDTO {
명명을  LottoDTO라고 정했는데 뭔가 상수들의 집합 같군요 
@Lee-YuGyeong  생각하시는 DTO에 대해서 한번 코멘트 달아주셨으면 좋겠습니다!

이러한 클래스는 Enum클래스가 어울리지 않을까?? 라고 조심스럽게 의견 제시해봅니다

2024-04-29 07:58 UTC, beng9re commented on src/main/java/Exam2/Lotto.java
> +public class Lotto {
Lotto를 관리하기 위한 Lotto 클래스 좋습니다 👍 

하지만, Lotto의 책임이 너무 많은거 같아요!! 
적절하게 분리하면 좋을꺼 같습니다

클래스를 분리해보고 합처보고 해보면 좋을꺼 같아요

2024-04-29 07:58 UTC, beng9re commented on src/main/java/Exam2/Lotto.java
> +        if (price < 1000) {
LottoDTO에 1000을 표기하는 상수가 있는거 같은데 그걸 활용해도 좋고 
클래스를 분리하면서 방법을 찾는게 좋아 보입니다!

2024-04-29 07:58 UTC, beng9re commented on src/main/java/Exam2/Lotto.java
> +            throw new RuntimeException("로또 구입 가격은 1000원 이상 이여야 합니다");
RuntimeException도 좋지만 표준 익셉션을 사용하면 좀 더 나타내기 편한 익셉션이 있을꺼 같아요!

2024-04-29 07:58 UTC, beng9re commented on src/main/java/Exam2/Lotto.java
> +    public List<Integer> makeLottoNumber() {
로또번호가 1과 45에 대한 매직넘버가 있는것 같습니다!

2024-04-29 07:58 UTC, beng9re commented on src/main/java/Exam2/Lotto.java
> +        List<List<Integer>> lottoNumberList = new ArrayList<>();
컬랙션에 컬랙션을 담는군요 
일급 컬랙션을 활용해보면 적절한 형태가 나올듯한데 적용해보시구 어떠한 장점을 가지는지 이야기해보면 좋을꺼 같습니다 :)

2024-04-29 07:58 UTC, beng9re commented on src/main/java/Exam2/Lotto.java
> +        if (winningStr.isEmpty()) {
저희 미션내용에는 

함수(또는 메소드)의 길이가 15라인을 넘어가지 않도록 구현한다.
함수(또는 메소드)가 한 가지 일만 잘 하도록 구현한다

다음과 같은내용이 있어요! 한번 검토 부탁드릴께요!

2024-04-29 07:58 UTC, beng9re commented on src/main/java/Exam2/Lotto.java
> +            sum += equalList.get(i) * LottoDTO.PRIZE[i];
i가 몇번째인지? i값은 뭐가 있을지 예상이 안되는거 같아요 좋은 방법이 있을꺼 같은데... 
한번 고민해보시는게 좋을꺼 같습니다. 이해가 안되시면 메신저나 코멘트 부탁드립니다 🙏

2024-04-29 07:58 UTC, beng9re commented on src/main/java/Exam2/Lotto.java
> +    public String benefit(double rate) {
메시지를 결정하는 것은 view의 역할에 어울리는것 같습니다!

2024-04-29 07:58 UTC, beng9re commented on src/test/java/Exam2/LottoTest.java
> +    void purchaseCount(int input, int expect) {
경계값을 잘 설정하시는군요 좋습니다!

2024-04-29 07:58 UTC, beng9re commented on src/test/java/Exam2/LottoTest.java
> +        for (Integer num : lottoNumber) {
앗... 테스트에 로직이 담겨있어요 
테스트에 로직이 담겨있으면 해당 로직은 어디서 체크하지라고? 생각이 들더라구요!

2024-04-29 07:58 UTC, beng9re commented on src/test/java/Exam2/LottoTest.java
> +}
앗 이런 파일끝에 공백이..

2024-04-29 07:58 UTC, beng9re commented on src/main/java/Exam2/Lotto.java
> +        Set<Integer> set = new HashSet<>(winningNumberList);
중복값 제거를 위한 Set 활용 좋습니다!

2024-04-29 07:58 UTC, beng9re commented on src/main/java/Exam2/Lotto.java
> +            if (!(num <= 45 && num > 0)) {
매직넘버로 인해 만약에 숫자가 45개가 넘는 제약조건으로 변경되면 변경 범위가 많아 지겠네요 ㅠ

2024-04-29 11:26 UTC, Lee-YuGyeong commented on src/main/java/Exam2/LottoDTO.java
> +public class LottoDTO {
DTO는 데이터의 정보를 담고있는 객체라고 생각합니다! @beng9re님 말씀처럼 상수들의 집합에는 enum이 더 어울릴거같네요!

2024-04-29 11:45 UTC, Lee-YuGyeong commented on src/main/java/Exam2/Lotto.java
> +        if (price < 1000) {
넵 상수로 표현해보겠습니다!

2024-04-29 11:46 UTC, Lee-YuGyeong commented on src/main/java/Exam2/Lotto.java
> +            throw new RuntimeException("로또 구입 가격은 1000원 이상 이여야 합니다");
IllegalArgumentException 사용해보도록 하겠습니다~!

2024-04-29 12:41 UTC, Lee-YuGyeong commented on src/main/java/Exam2/Lotto.java
> +        List<List<Integer>> lottoNumberList = new ArrayList<>();
일급 컬렉션을 적용하니 코드 가독성이 향상되어 좋은 것 같습니다! 또한, 컬렉션의 내부 구조를 클래스 안에 숨길 수 있어서 유연성도 증대된거같아요~!

2024-04-29 12:50 UTC, beng9re commented on src/main/java/Exam2/LottoDTO.java
> +public class LottoDTO {
DTO(Data Transfer Object)는 데이터 전송 객체라고 합니다. 
데이터를 레이어간 `전달`하는 용도로 많이 사용합니다.

![image](https://github.com/Doolki/java-lotto/assets/26699273/4329fa49-d6ea-4d15-9575-9da9eb52f740)

https://velog.io/@taehee-kim-dev/DTO-vs-VO 관련글도 한번 참조해주세요

2024-04-29 14:27 UTC, Lee-YuGyeong commented on src/main/java/Exam2/Lotto.java
> +        if (winningStr.isEmpty()) {
예외처리 하는 부분들을 다른 파일로 빼는게 좋을까요 ??

2024-04-29 16:21 UTC, beng9re commented on src/main/java/Exam2/Lotto.java
> +        if (winningStr.isEmpty()) {
힌트: 로또에는 로또번호라는 개념이 있을꺼 같아요!

2024-04-30 16:59 UTC, Lee-YuGyeong commented on src/main/java/Exam2/Lotto.java
> +        if (winningStr.isEmpty()) {
여러 예외사항 들을 "로또 번호 형식에 맞지않는다" 라는 예외사항 하나로 묶어야 하는 걸까요??

2024-04-30 16:59 UTC, Lee-YuGyeong commented on src/main/java/Exam2/Lotto.java
> +            sum += equalList.get(i) * LottoDTO.PRIZE[i];
foreach 구문을 사용해야하는 걸까요?ㅠㅠ

2024-04-30 17:01 UTC, Lee-YuGyeong commented on src/main/java/Exam2/Lotto.java
> +            if (!(num <= 45 && num > 0)) {
if (!(num <= lottoEndNumber && num >= lottoStartNumber))

2024-05-01 01:33 UTC, beng9re commented on src/main/java/Exam2/Lotto.java
> +        if (winningStr.isEmpty()) {
힌트가 어려우셨군요! 
예외에 초점을 가지시기 보다 

하나의 로또에는 6개의 로또 번호(개념)으로 이루어져 있자나요?
로또번호개념을 가진 로또번호 클래스로 분리하고 로또번호에 대한 비지니스로직을 합처보는게 어떤가 하는거였습니다!

2024-05-01 01:38 UTC, beng9re commented on src/main/java/Exam2/Lotto.java
> +            sum += equalList.get(i) * LottoDTO.PRIZE[i];
equalList는 List 자료구조를 채택하고 있어서 첫번째 인덱스가 1개를 맞춘건가? 6개를 맞춘건가? 이해하기 어려운거 같아요!

enum클래스를 제안 드렸던것 처럼 1등, 2등, 3등을 enum클래스의 상수로 선언 해두고 속성들을 당첨갯수와 금액을 관리하게 된다면?
어떨까요?!

2024-05-01 02:20 UTC, beng9re requested changes
> 열심히 고쳤으나... 어려운 부분들은 코멘트 남겨두었습니다! 한번만 확인해주시면 감사하겠습니다 ㅠ.ㅠ
> 미션1은......! 조금 있다가 다시 수정하겠습니다!! (안하는거 XXX 까먹은거 XXX)
잘 알고 있습니다!
조금 지칠수도 있지만 힘내주세요!

피드백 확인해보시구 재요청 부탁드릴께요! 

객체지향프로그래밍에서는 객체들끼리 서로 `협력`하면서 역할을 수행한답니다. 즉 메서드(메시지)를 통해서 소통을 해요 적절한 객체가 있다면 옮겨주고 새로운 개념및 역할이 나온다면 분리해보고 해보면 좋을꺼 같아요

2024-05-01 02:20 UTC, beng9re commented on src/main/java/exam2/lotto/LottoPrize.java
> +public enum LottoPrize {
LottoPrize라는 Enum이 추가가 되었군요! 피드백 반영 좋습니다!

2024-05-01 02:20 UTC, beng9re commented on src/main/java/exam2/lotto/LottoPrize.java
> +    PRIZE(new int[]{0, 0, 0, 5000, 50000, 1500000, 2000000000});
자바에 숫자에 대한 관리는 5_000 => 5000으로 인식하기도 한답니다. 
적용하시면 금액이니까 보기에 편할꺼 같아요

enum이 익숙하지 않으셔서 어려움을 느끼신 흔적이 보이네요 ㅠㅠ
LottoPrize에 대한 enum이니 등수 혹은 갯수로 관리하면 편할꺼 같습니다.
아래 코드 참조해보세요~
```java
public LottoPrize {
    1등(2_000_000_000), 
    2등(15_000),
     .....;
    
    private final int 당첨금액;
}


```

2024-05-01 02:20 UTC, beng9re commented on src/main/java/exam2/lotto/PurchaseLottoList.java
> +    private final static int lottoEndNumber = 45;
매직변수 추출 좋습니다.  👍 

로또번호의 범위가 변경될때 메서드까지 안내려다 보고 상위에서 제어하면 되겠군요!
상수의 컨벤션은 대문자 SNAKE UPPER형식이 컨벤션이에요 피드백 수정하시다가 놓치신거 같아요 ㅠㅠ

```suggestion
private final static int LOTTO_START_NUMBER = 1;
private final static int LOTTO_END_NUMBER = 45;
```

2024-05-01 02:20 UTC, beng9re commented on src/main/java/exam2/lotto/PurchaseLottoList.java
> +    public PurchaseLottoList() {
해당 기본 생성자는 불완전한 객체를 만드는거 같아요 ㅠㅠ

2024-05-01 02:20 UTC, beng9re commented on src/main/java/exam2/lotto/PurchaseLottoList.java
> +    public int isEqual(int lottoNum, WinningLottoNumber winningLottoNumber) {
isXXX 라는 메서드 컨벤션은 boolean값을 반환할꺼 같은데 int형으로 반환하는군요.
이에 맞추어 변경해주면 좋을꺼 같습니다

2024-05-01 02:20 UTC, beng9re commented on src/main/java/exam2/lotto/PurchaseLottoList.java
> +    public List<List<Integer>> getNumberList() {
아실수도 있겠지만 선언 순서가 있는데요 
게터와 세터는 맨 아랫부분에 위치합니다.

참고 자료: https://dodop-blog.tistory.com/277

2024-05-01 02:20 UTC, beng9re commented on src/main/java/exam2/lotto/WinningLottoNumber.java
> +public class WinningLottoNumber {
생각하기 어려우셨을텐데 로또 당첨번호라는 클래스가 생겼군요! 

저희 여기서 한번 추상화 해봅시다!

LottoNumbers라는 클래스 이름으로 수정해보고 PurchaseLottoList 클래스에 
인스턴스 변수를 LottoNumbers 포함시킨다면 로또 번호 자체에 대한 관리는  `LottoNumbers`에서 
당첨, 구매, 여러가지에 대한 일은 PurchaseLottoList에서 역할을 분리해주는 효과가 나올꺼 같아요

2024-05-01 02:20 UTC, beng9re commented on src/main/java/exam2/lotto/WinningLottoNumber.java
> +public class WinningLottoNumber {
이렇게 된다면 PurchaseLottoList라는 명명이 바뀔수도 있겠네요!

2024-05-01 02:21 UTC, beng9re commented on src/main/java/Exam2/Lotto.java
> +            if (!(num <= 45 && num > 0)) {
> 매직 넘버를 사용해서 코드를 수정하면 변경 범위가 줄어드니 매직 넘버를 사용해보라는 것 일까요?!

넵 맞습니다!

2024-05-03 06:55 UTC, Lee-YuGyeong reviewed
리뷰해주세요!!!!!!!!!!리뷰해주세요!!!!!!!!!!리뷰해주세요!!!!!!!!!!리뷰해주세요!!!!!!!!!!리뷰해주세요!!!!!!!!!!리뷰해주세요!!!!!!!!!!리뷰해주세요!!!!!!!!!!리뷰해주세요!!!!!!!!!!리뷰해주세요!!!!!!!!!!리뷰해주세요!!!!!!!!!!리뷰해주세요!!!!!!!!!!

2024-05-04 01:44 UTC, beng9re requested changes
코멘트들 남겼으니 확인해보시구 재요청 부탁드릴께요!

2024-05-04 01:44 UTC, beng9re commented on src/main/java/Exam1/CalculatorService.java
> +    private final CalculatorValidate calculatorValidate;
피드백 반영 좋습니다 👍

2024-05-04 01:44 UTC, beng9re commented on src/main/java/exam2/lotto/LottoNumbers.java
> +    public final static int LOTTO_END_NUMBER = 45;
아실수도 있겠지만 public static final 순서로 작성하는게 컨벤션입니다!
```suggestion
    public static final int LOTTO_START_NUMBER = 1;
    public static final int LOTTO_END_NUMBER = 45;
```

2024-05-04 01:44 UTC, beng9re commented on src/main/java/exam2/lotto/LottoNumbers.java
> +public class LottoNumbers {
LottoNumbers를 관리하는 로또 번호들 클래스가 생겼군요 
로또 번호 관련로직들을 이제 모을수 있겠네요! 💯

2024-05-04 01:44 UTC, beng9re commented on src/main/java/exam2/lotto/LottoNumbers.java
> +    //개수 만큼 랜덤 로또 번호를 생성합니다.
설명이 필요한 주석은 javadoc 주석을 사용하는 편이에요~
```suggestion
/* 
* 개수 만큼 랜덤 로또 번호를 생성합니다.
*/
```

2024-05-04 01:44 UTC, beng9re commented on src/main/java/exam2/lotto/LottoNumbers.java
> +    private List<List<Integer>> numberList = new ArrayList<>();
일급컬랙션의 인스턴스 변수를 
`List<Integer>> numberList = new ArrayList<>();`
여기까지 사용하는것에 대해서 어떻게 생각하시나요?

2024-05-04 01:44 UTC, beng9re commented on src/main/java/exam2/lotto/Purchase.java
> +    private List<Integer> equalList;
LottoPrize라는 enum클래스가 생겼으니 
해당 자료구조를 Map<LottoPrize, Integer>와 같은 구조로 변경하시면 아랫부분에서 lottoEqualList 메서드에서 몇번째가 어떤 값인지 쉽게 알 수 있을꺼 같은데 어떻게 생각하시나요?

2024-05-04 01:44 UTC, beng9re commented on src/test/java/exam2/LottoTest.java
> +class LottoTest {
테스트코드 꼼꼼하게 잘 작성해주었습니다!

Lotto클래스가 사라지기도 했고 
Lotto와 관련된 테스트만 있는것 같지 않아보여요 ~

각 클래스가 생긴것 처럼 테스트 코드도 분리가 필요해보여요~

2024-05-04 01:44 UTC, beng9re commented on src/main/java/exam2/lotto/Winning.java
> +    public Winning() {
해당 기본 생성자는 없어도 되지 않을까요?

2024-05-08 00:12 UTC, Lee-YuGyeong reviewed
리뷰 요청합니다

2024-05-08 00:12 UTC, Lee-YuGyeong commented on src/main/java/exam2/lotto/LottoPrize.java
> +    ZERO(0),
zero(0,0)
one(1,0)

2024-05-08 00:12 UTC, Lee-YuGyeong commented on src/main/java/exam2/lotto/LottoPrize.java
>      }
맞춘 개수를 파라미터를 넘기는 메소드를 추가

2024-05-08 00:12 UTC, Lee-YuGyeong commented on src/main/java/exam2/lotto/PurchaseLottoList.java
> +    public PurchaseLottoList() {
테스트 코드를 이렇게 작성해서 저기 기본 생성자를 넣었는데 기본생성자를 지우고 테스트 코드 생성방식을 바꾸면 될까요?ㅠ

Purchase purchase = new Purchase() {{
            add(Arrays.asList(8, 21, 23, 41, 42, 43));
            add(Arrays.asList(3, 5, 11, 16, 32, 38));
        }};

2024-05-08 00:12 UTC, Lee-YuGyeong commented on src/main/java/exam2/lotto/PurchaseLottoList.java
> +    public int isEqual(int lottoNum, WinningLottoNumber winningLottoNumber) {
int형을 반환해서 해당 메서드를 호출하는 곳에

equalCount += isEqual(lottoNum, winning);

이렇게 더해줄려고 하는데 메서드 이름을 바꾸면 될까요?!

2024-05-08 00:12 UTC, Lee-YuGyeong commented on src/main/java/Exam1/CalculatorService.java
>      }
DI 부분 수정하여 다시 올립니다!

2024-05-08 00:12 UTC, Lee-YuGyeong commented on src/main/java/exam2/lotto/Purchase.java
> +    private List<Integer> equalList;
Map<LottoPrize, Integer> 로 코드를 변경해보니 정보들을 저장하고 표현하기 훨 좋은 것같습니다!

2024-05-08 00:12 UTC, Lee-YuGyeong commented on src/main/java/exam2/lotto/LottoNumbers.java
> +    private List<List<Integer>> numberList = new ArrayList<>();
List<Integer>> numberList = new ArrayList<>() 이렇게 변경하니 get을 여러번 사용하지 않아서 좋은 것 같아요~~!

2024-05-08 00:12 UTC, Lee-YuGyeong commented on src/main/java/exam2/lotto/Winning.java
> +    public Winning() {
넵 삭제했습니다!

2024-05-08 00:12 UTC, Lee-YuGyeong commented on src/test/java/exam2/LottoTest.java
> +class LottoTest {
넵~ 분리했습니다!

2024-05-11 12:26 UTC, beng9re requested changes

2024-05-11 12:26 UTC, beng9re commented on src/main/java/exam2/lotto/PurchaseLottoList.java
> +    public PurchaseLottoList() {
List<Lottonumbers> 다음과 같은 인수로 생성자를 만들어보면 어떨까요?

2024-05-11 12:26 UTC, beng9re commented on src/main/java/exam2/lotto/PurchaseLottoList.java
> +    public int isEqual(int lottoNum, WinningLottoNumber winningLottoNumber) {
matchedLottoNumberCount 같은 메서드명과 같이 써보면 좋을꺼 같아요
제가 그냥 생각나는 단어쓴거이니 한번 고려해보시면 좋을꺼 같습니다

2024-05-14 10:32 UTC, beng9re commented
temp

2024-05-15 09:54 UTC, Lee-YuGyeong commented on src/main/java/exam2/lotto/PurchaseTicket.java
> +    public static PurchaseTicket createAutoLottoNumber(int price) {
생성자부분 수정하였습니다!

2024-05-15 09:55 UTC, Lee-YuGyeong reviewed
코드 수정하였습니다 ~~

2024-05-15 15:31 UTC, beng9re requested changes
전체적으로 피드백 반영하여 메서드명과 변수명 신경 쓴 부분 인상깊었습니다!

다음 단계에서 코멘트를 처리해도 좋지만 한번 더 확인하는 차원에서 
일단 `Request changes` 하겠습니다.

다음 단계 진행하고 싶으시면 코멘트 부탁드려요!

2024-05-15 15:31 UTC, beng9re commented on src/main/java/exam1/CalculatorValidate.java
>      public void isPositive(int num) {
이친구의 이름은 아직 ㅠㅠ is이군요

2024-05-15 15:31 UTC, beng9re commented on src/main/java/exam2/lotto/LottoNumbers.java
> +        String[] numberArray = inputNumbers.split(",");
변수명에는 타입을 쓰지 않는다 라고 주제가 있는데요.
그 이유는 자바는 강타입 언어로 타입이 이미 존재하기 때문이에요 
https://80000coding.oopy.io/7a0a2aeb-367a-49e8-874c-403025687071 이 부분 참조 부탁드릴께요

2024-05-15 15:31 UTC, beng9re commented on src/main/java/exam2/lotto/LottoNumbers.java
> +    private List<Integer> checkValidRange(String[] inputNumbers) {
이제 check라는 의미가 부여되어 안에 체크하는 로직임을 알 수 있겠네요 👍

2024-05-15 15:31 UTC, beng9re commented on src/main/java/exam2/lotto/PurchaseTicket.java
> +        }
```suggestion
            for (LottoNumbers lottoNumbers : lottoNumbersList) {
                  int count = (int) lottoNumbers.getNumberList().stream()
                    .filter(lottoNum -> winning.getLottoNumbers().getNumberList().contains(lottoNum))
                    .count();
                   
                  // 한 템포 쉬어가기
                  LottoPrize lottoPrize = LottoPrize.getLottoPrize(count);
      
                  this.matchCount.put(lottoPrize, this.matchCount.get(lottoPrize) + 1);
            }
```
for i > for each문으로 변경하면
다음과 같이 작성해볼수도 있을꺼 같아요.

그리고, 필터부분의 LottoNumbers클래스에서 해당 로또번호가 있는지 없는지 판별하는 메서드가 있으면 조금더 간결하게 표현이 될꺼 같아요

2024-05-15 15:31 UTC, beng9re commented on src/main/java/exam2/lotto/PurchaseTicket.java
> +    public static PurchaseTicket createAutoLottoNumber(int price) {
템플릿 팩토리 메서드 패턴을 사용해서 명확한 이름을 가지는군요 좋습니다 👍

2024-05-15 15:31 UTC, beng9re commented on src/main/java/exam2/lotto/PurchaseTicket.java
> +    public void rate() {
getRate에 해당 로직을 넣을수도 있을꺼 같은데 
별도로 생성한 이유가 있을까요? (틀렸다는건 아니고 궁금합니다)

2024-05-15 15:31 UTC, beng9re commented on src/main/java/exam2/lotto/LottoPrize.java
> +        return LottoPrize.values()[index];
```suggestion
           return Arrays.stream(LottoPrize.values())
                .filter((it) -> it.equalIndex(index))
                .findFirst()
                .orElse(LottoPrize.ZERO);
```
다음과 같이 작성하면 index의 위치가 변화 되더라도 대응이 가능할꺼 같아요!

2024-05-15 15:31 UTC, beng9re commented on src/main/java/exam2/lotto/LottoService.java
> +    public void calculateEqualListAndRate() {
로또 서비스가 PurchaseTicket, WinningNumber를 가지고 있는게 적절할까에 대해서 한번 생각해보시면 좋을꺼 같아요.
해당 메서드에서 파라미터로 PurchaseTicket, WinningNumber을 받아서 처리를 할 수도 있을꺼 같아서요

2024-05-15 15:31 UTC, beng9re commented on src/test/java/exam2/lotto/WinningTest.java
> +class WinningTest {
안쓰는 클래스는 지우는게 좋아보여요~

2024-05-15 15:31 UTC, beng9re commented on src/test/java/exam2/lotto/PurchaseTest.java
> +class PurchaseTest {
클래스의 이름이 변경되었다면 이부분도 같이 변경해주시면 좋을꺼 같아요!

2024-05-21 12:42 UTC, Lee-YuGyeong commented on src/main/java/exam2/lotto/PurchaseTicket.java
> +    public void rate() {
아무 생각이 없었어요..! ㅠ

2024-05-21 12:42 UTC, Lee-YuGyeong commented on src/main/java/exam2/lotto/PurchaseTicket.java
> +    public void rate() {
getRate로 수정했습니다!

2024-05-21 14:50 UTC, Lee-YuGyeong reviewed
다음단계로 넘어가고싶어요!!

2024-05-21 14:59 UTC, beng9re approved these changes
이번단계는 머지하겠습니다~

다음단계 진행하면서 수정하실곳 있으면 수정해주세요~

2024-05-21 14:59 UTC, beng9re commented on src/main/java/exam2/lotto/LottoNumbers.java
> +    public LottoNumbers(List<Integer> numberList) {
생성자가 여러개 인데 한곳에서 처리할수는 없을까요? 
부생성자 주생성자를 한번 생각해보세요

2024-05-21 15:04 UTC, merged

2024-05-21 15:04 UTC, beng9re commented
다음단계 진행해주세요