미션2_로또 게임 자동
Doolki/java-lotto pull request #8
Opened 2024-04-30 00:43 UTC by babysean

# 변경 이유
미션 2 - 로또 게임 자동 기능 개발

# 변경의 종류
- [ ] 버그 수정 (Bug fix)
- [x] 새 기능 (New feature)
- [ ] 기능 변경(Modification of the existing feature)
- [x] 리팩터링(Refactoring)

# 변경 내용
- 로또 1회 가격은 1,000원, 로또 번호는 1 ~ 45 사이 입니다.
- 구입 금액을 입력받고 구매 가능한 수량을 안내합니다.
- 구매 가능 수량 만큼, 6개의 중복되지 않은 랜덤 정수를 생성합니다.
- 지난주 당첨 번호를 입력 받습니다.
- 구매한 로또 번호 목록과 지난주 당첨 번호를 비교합니다.
- 일치하는 개수 만큼 카운트를 출력합니다. (3, 4, 5, 6개 일치하는 개수 출력)
- 수익률를 계산하여 출력합니다.

# 기대 효과
- 로또 게임을 수행할 수 있다.

# 주요사항
- 메서드와 클래스를 잘 나누었는지 피드백이 필요합니다.
- 테스트 코드에 대한 피드백이 필요합니다.

# 코드 품질
- [x] 변경 사항을 자체적으로 리뷰했습니다.
- [x] 변경 사항을 로컬에서 테스트 했습니다.
- [x] 코드의 이해를 돕기 위해 적절한 곳에 주석을 작성했습니다.
- [x] 커밋은 이해하기 쉬운 순서와 적절한 크기로 분리했습니다.

#테스트 과정
1. `PlayLotto.java`의 main 메서드를 실행합니다.
2. 구매 금액을 입력받고 구매 개수와 구매한 로또 번호를 출력 받습니다.
3. 지난 주 로또 당첨 번호를 입력합니다.
4. 구매한 로또 번호와 지난주 로또 당첨 번호를 비교하여 맞춘 개수와 수익률을 출력합니다.

2024-05-01 01:28 UTC, beng9re requested changes
미션 2에 대한 구현 고생하셨습니다!

학습테스트를 진행하면서 클래스를 구현한 흔적이 인상 깊었어요!
학습테스트를 넘어서 실제 클래스의 기능들을 테스트 하는 부분을 추가해주었으면 좋겠습니다!

그 이유는 만약에 다른 사람이 Lotto 클래스를 사용하거나 수정하게 된다면 기능 테스트가 있는 클래스를
신뢰하고 사용할 수 있을꺼 같습니다 : )

또한, 객체지향은 객체들의 역할들을 통해서 협력을 진행한다고 해요.

현재 @babysean 님이 작성해주신 클래스는 딱 하나의 Lotto 클래스만 관리하고 있습니다!
Lotto 클래스의 역할을 보시면 로또 검증도하고, 당첨금 계산도하고, 로또도 만들고 
역할이 너무 많은것 같아요! 
( 힌트: 로또번호에 대한 개념 )

한번 리팩토링 진행해보시고 재요청 부탁드리겠습니다 🙇‍♂️

2024-05-01 01:28 UTC, beng9re commented on src/main/java/lotto/Lotto.java
> +    private final Integer purchasePrice;
구매할 금액과 구매 갯수가 Wrapper 클래스로 되어있군요 프리미티브 타입을 쓸수도 있었을꺼 같은데 
Wrapper 클래스로 선언하신 이유가 있을까요?

2024-05-01 01:28 UTC, beng9re commented on src/main/java/lotto/Lotto.java
> +        for (int i = 1 ; i <= 45 ; i++) {
지금 1과 45에 대한 매직넘버가 있는거 같습니다!
만약에 숫자의 범위가 1~45가 아니고 다른 범위가 존재하면 해당 메서드까지 봐서 고처야할꺼 같아요! 

매직넘버 참조링크: https://blog.naver.com/coding_elmo/222453941287

2024-05-01 01:28 UTC, beng9re commented on src/main/java/lotto/Lotto.java
> +                    Set<Integer> copyOfPurchaseNumber = new HashSet<>(purchaseNumber);
잘 생각해보시면 로또번호에는 중복이 발생하지 않는 특징을 가지고 있어요 
이러한 부분에 적절한 자료구조중에 하나가 Set인데요 로또번호를 Set 컬랙션으로 관리를 하게 된다면 불필요하게 Copy하는 부분을 제거할수 있을꺼 같아요!

2024-05-01 01:28 UTC, beng9re commented on src/main/java/lotto/Lotto.java
> +                    winningCount.add(copyOfPurchaseNumber.size());
맞춘갯수를 HashMap으로 관리하게 되면 더 좋지 않을까요?!

2024-05-01 01:28 UTC, beng9re commented on src/main/java/lotto/Lotto.java
> +        int winningPrice = getWinningCount(3) * 5000
수익률 부분에서도 만약에 수익율이 변경이 된다면 유지보수 하기 어렵지 않을까? 라는 생각을 해봅니다 
이러한 부분을 enum클래스로 관리하면 더좋을꺼 같습니다!

2024-05-01 01:28 UTC, beng9re commented on src/test/java/lotto/LottoTest.java
> +    void 구매_금액은_1000_과_같거나_커야_합니다() {
이 부분의 테스트는 어떤 테스트인건가요?!

2024-05-01 01:28 UTC, beng9re commented on src/test/java/lotto/LottoTest.java
> +    void 당첨번호는_콤마로_구분된_6개_정수_입니다() {
학습테스트가 끝나면 테스트코드로 리펙토링을 하여 해당 기능을 테스트하는 로직으로 변경하면 좋을꺼 같아요!
테스트코드도 유지보수 대상이에요!

2024-05-01 01:28 UTC, beng9re commented on src/main/java/lotto/Lotto.java
> +public class Lotto {
저희 객체지향 생활체조의 규칙중 
`규칙 7: 3개 이상의 인스턴스 변수를 가진 클래스를 쓰지 않는다.` 라는 항목이 있는데요 
작성해주신 인스턴스 변수가 3개보다 많은것 같아요.

3개이상 쓰지 말라는 이유는 해당 객체의 해당 인스턴스를 관리하는 책임이 많아지기 때문이에요 
이 부분은 적절한수준에서 클래스를 분리해라와 같은데요. 
한번 분리를 진행해보면 좋을꺼 같습니다

2024-05-02 01:43 UTC, babysean commented on src/main/java/lotto/Lotto.java
> +    private final Integer purchasePrice;
래퍼 클래스로 통일 시켜서 보기 좋게 하기 위함이였어요

생각해보니 과도한 코딩인 것 같아요 ㅎㅎ 기본 타입으로 변환해볼게요

2024-05-02 01:48 UTC, babysean commented on src/test/java/lotto/LottoTest.java
> +    void 구매_금액은_1000_과_같거나_커야_합니다() {
"구매 금액은 1000원 이상 입력되어야한다"는 조건을 위한 테스트 였어요

메서드를 사용해서 명확하게 변경해볼게요

2024-05-03 04:48 UTC, babysean commented on src/main/java/lotto/Lotto.java
> +        for (int i = 1 ; i <= 45 ; i++) {
매직넘버를 제거하고 상수를 사용하도록 변경할게요 !

2024-05-03 04:51 UTC, babysean commented on src/test/java/lotto/LottoTest.java
> +    void 당첨번호는_콤마로_구분된_6개_정수_입니다() {
네 ! 학습테스트가 종료되었으니, 실제 기능을 테스트할 수 있도록 리팩토링할게요 !

2024-05-03 07:33 UTC, babysean commented on src/main/java/lotto/Lotto.java
> +        int winningPrice = getWinningCount(3) * 5000
네 ! enum 클래스로 변경해서 리팩토링 할게요 !

2024-05-03 07:49 UTC, babysean commented on src/main/java/lotto/Lotto.java
> +                    Set<Integer> copyOfPurchaseNumber = new HashSet<>(purchaseNumber);
넵 Set 자료형으로 해결해볼게요 ! ㅎㅎ (사실 이름만 copy에요)

2024-05-05 06:20 UTC, babysean commented on src/main/java/lotto/Lotto.java
> +                    winningCount.add(copyOfPurchaseNumber.size());
List로 하여 몇개 맞았는지에 대한 숫자만 저장하도록 소스 수정했어요
예) 구매한 로또가
  {1,2,3,4,5,6} {1,2,3,14,15,16}{21,22,23,24,25,26} 이고
  지난주 당첨 번호가 {1,2,3,34,35,36} 일 경우, List<Integer> winningCount에 {3, 3} 이 저장됩니다 !

그 이후 winningCount에 필요한 숫자가 몇개인지 계산해서 가져오면 편할 것 같습니다 !
우선 push 했으니 로직 한 번 확인해주시고

문제 있다면 말씀 부탁 드릴게요 😄

2024-05-05 06:21 UTC, babysean commented
리뷰 부탁 드립니다 🙏🏼

2024-05-05 09:34 UTC, beng9re requested changes
피드백 반영 좋습니다! 

한번 생각할거리 코멘트로 남겨두었으니 재요청 부탁드릴께요!

2024-05-05 09:34 UTC, beng9re commented on src/main/java/lotto/view/InputView.java
> +    private void validate(String[] number) {
이러한 로직들은 비지니스 로직으로써 view 역할은 아닌것 같아요 
view는 화면에 대한 로직만 담겨 있었으면 좋겠다 라고 생각이 듭니다!

2024-05-05 09:34 UTC, beng9re commented on src/main/java/lotto/domain/LottoNumberGenerator.java
> +public class LottoNumberGenerator {
로또 번호를 생성을 위한 팩토리 클래스 좋네요!

2024-05-05 09:34 UTC, beng9re commented on src/main/java/lotto/domain/LottoPrize.java
> +public enum LottoPrize {
로또 보상에 대한 enum클래스 좋네요

2024-05-05 09:34 UTC, beng9re commented on src/main/java/lotto/domain/LottoPurchase.java
> +    private List<List<Integer>> purchasedNumbers = new ArrayList<>();
List<Integer> purchasedNumbers를 일급컬랙션으로 추출하면 어떻게 될까요?

2024-05-05 09:34 UTC, beng9re commented on src/test/java/lotto/LottoTest.java
> +class LottoTest {
클래스가 분리 된 만큼 테스트 클래스도 분리해야 관리가 편하다고 생각하고 
어떤 테스트인지 더 명확하게 될꺼 같습니다!

2024-05-05 09:34 UTC, beng9re commented on src/test/java/lotto/LottoTest.java
> +        InputView inputView = new InputView();
View 까지 테스트를 진행하셨군요 좋습니다!

2024-05-05 09:34 UTC, beng9re commented on src/main/java/lotto/service/LottoService.java
> +public class LottoService {
약간 경계가 모호한거 같기도 한거 같네요 
컨트롤러역할과 서비스 역할이 합처진거 같아요

컨트롤러에서는 서비스 만 호출하고 view에 데이터만 전달하는 역할로 수행하고

서비스에서는 해당 도메인(비지니스 로직)을 이어주는 역할로 한번 구성해보시는건 어떨까요?

2024-05-05 13:50 UTC, babysean commented on src/test/java/lotto/LottoTest.java
> +        InputView inputView = new InputView();
scanner를 테스트하는 방법을 새롭게 배웠어요 !! 😁

2024-05-05 13:51 UTC, babysean commented on src/main/java/lotto/domain/LottoPrize.java
> +public enum LottoPrize {
"enum 클래스를 써야겠다"라고 아직은 바로바로 생각나지 않는 것 같아요 😅

2024-05-05 13:52 UTC, babysean commented on src/main/java/lotto/domain/LottoNumberGenerator.java
> +public class LottoNumberGenerator {
객체화를 하니 어렵지만 코드가 이해하기 쉽고 깔끔해지는 것 같아서 좋아요 !

2024-05-06 04:26 UTC, babysean commented on src/main/java/lotto/view/InputView.java
> +    private void validate(String[] number) {
유효성 체크하는 로직을 클래스로 분리하여 구현해볼게요 !

2024-05-06 04:35 UTC, babysean commented on src/main/java/lotto/domain/LottoPurchase.java
> +    private List<List<Integer>> purchasedNumbers = new ArrayList<>();
현재는 LottoPurchase 클래스는 List<List<Integer>> 에 의존성을 갖고 있어요.
그래서 List<List<Integer>> 구현이 변경되면 LottoPurchase 클래스도 변경되어야하는 문제점이 있어요 !

purchasedNumbers 를 일급컬렉션으로 바꿔서 리팩토링 해볼게요 👍🏼

2024-05-06 05:16 UTC, babysean commented on src/test/java/lotto/LottoTest.java
> +class LottoTest {
테스트 코드를 클래스별로 분리 해볼게요 !

2024-05-06 05:25 UTC, babysean commented on src/main/java/lotto/service/LottoService.java
> +public class LottoService {
이해는 되었지만 어떻게 구성해야 좋을지 잘 모르겠어요 😞 
혹시 내일 같이 봐주실 수 있으신가요 ?

2024-05-06 05:25 UTC, beng9re commented on src/main/java/lotto/domain/LottoNumberGenerator.java
> +public class LottoNumberGenerator {
지금 상황에서 찾아보면 좋은 글이 있어서 공유드려요 

https://inpa.tistory.com/entry/GOF-%F0%9F%92%A0-%ED%8C%A9%ED%86%A0%EB%A6%AC-%EB%A9%94%EC%84%9C%EB%93%9CFactory-Method-%ED%8C%A8%ED%84%B4-%EC%A0%9C%EB%8C%80%EB%A1%9C-%EB%B0%B0%EC%9B%8C%EB%B3%B4%EC%9E%90#%EC%98%88%EC%A0%9C%EB%A5%BC_%ED%86%B5%ED%95%B4_%EC%95%8C%EC%95%84%EB%B3%B4%EB%8A%94_factory_method_%ED%8C%A8%ED%84%B4

2024-05-06 05:27 UTC, babysean commented
컨트롤러 역할과 서비스 역할 구분 제외하고 리뷰 부탁 드립니다 !

내일 시간 되실 때 같이 한 번만 확인 부탁 드릴게요 😢

2024-05-06 07:27 UTC, beng9re reviewed
한번더 확인 부탁드릴께요 :)

저희가 제일 중요하게 생각하는 부분은 핵심 비지니스 로직이 담겨있는 domain패키지 아래에 있는 
클래스들이라고 생각해요! 이 부분의 테스트는 꼭 필요하다고 생각하고 있답니다.

주요 논의 거리는 내일 같이 이야기 해봅시다!

2024-05-06 07:27 UTC, beng9re commented on src/main/java/lotto/domain/Validator.java
> +public class Validator {
유효성 검증을 위한 클래스가 추출이 되었군요 
근데 클래스 이름이 Validator라는 클래스여서 어떠한 정보를 가진 Validator인지?
알아보기는 어려울꺼 같습니다.

2024-05-06 07:27 UTC, beng9re commented on src/main/java/lotto/domain/PurchasedNumbers.java
> +    private final List<List<Integer>> purchasedNumbers = new ArrayList<>();
List<Integer>> purchasedNumbers까지만 일급컬랙션으로 해보자라는 의도였는데 
구매한 로또 번호들과 당첨 로또 번호에 활용 할 수 있을꺼 같아서요!

2024-05-06 07:27 UTC, beng9re commented on src/main/java/lotto/domain/Validator.java
> +    public Validator(String[] number) {
생성자 보다는 메서드 (행위)에 어울리는거 같아요 

다음 회차에 로또 번호가 나타나면 해당 객체가 여러번 생성되어 체크될꺼 같은데
어떻게 생각하시나요?

2024-05-06 07:27 UTC, beng9re commented on src/main/java/lotto/service/LottoService.java
> +    public static final int MIN_LOTTO_NUMBER = 1;
로또번호에 대한 일급컬랙션이 하나 생성이 되면 해당 상수또한 해당 클래스로 이관이되어 
응집도 있는 클래스가 될꺼 같네요

2024-05-07 05:47 UTC, babysean commented on src/main/java/lotto/domain/Validator.java
> +public class Validator {
명확하게 LastWeekLottoNumberValidator 로 변경할게요 !

2024-05-07 07:10 UTC, babysean commented on src/main/java/lotto/domain/Validator.java
> +    public Validator(String[] number) {
여러 회차를 진행한다고 가정하였을 때, 생성자는 인스턴스를 매번 만들어야하므로 비효율적인 것 같습니다 ! 메서드로 변경할게요

2024-05-11 06:48 UTC, babysean commented
리뷰 부탁 드려요 🙏🏼

2024-05-11 12:18 UTC, beng9re requested changes
의지 확인했습니다🔥 코멘트 보시구 한번더 리뷰요청 부탁드릴께요

2024-05-11 12:18 UTC, beng9re commented on src/main/java/lotto/service/LottoService.java
> +        return new LottoTicket(numberList);
LottoTicket의 생성자에서 `String[]`타입을 인수로 받아 로또 티켓을 만든다면 생성의 책임을 LottoTicket으로 모을수 있을꺼 같아요!

2024-05-11 12:18 UTC, beng9re commented on src/main/java/lotto/service/LottoService.java
> +        LottoCalculator calculator = new LottoCalculator();
LottoCalculator클래스는 메서드마다 계속 반복되어 생성하는군요 제가 본 `LottoCalculator`클래스는 상태를 가지지 않고 
계산의 책임만 가지고 있는데 이 부분을 의존주입형태로 활용해보면 좋을꺼 같습니다 :)

2024-05-11 12:18 UTC, beng9re commented on src/main/java/lotto/service/LottoService.java
> +        return Math.floor(rateOfReturn * 1000) / 1000;
LottoCalculator라는 클래스를 만드셨으니 계산에 대한것 `수익률`계산또한 모아보는것도 어떨까요?

2024-05-11 12:18 UTC, beng9re commented on src/main/java/lotto/view/InputView.java
> +    public static final int LOTTO_PRICE = 1000;
주석은 로또 개수인데 ㅠㅠ 로또 가격이군요 ㅠㅠ
개인적으로 해당 상수는 로또 티켓에 있는게 어울려 보입니다!

2024-05-11 12:18 UTC, beng9re commented on src/main/java/lotto/domain/LottoTicket.java
> +public class LottoTicket {
로또 티켓 좋습니다! 이제 로또 티켓에 대한 내용들을 모을수 있겠군요!

2024-05-11 12:18 UTC, beng9re commented on src/main/java/lotto/LottoApplication.java
> +    private final LottoConsumer consumer;
변하지 않는것에 대한 final 처리 좋습니다!

2024-05-11 12:18 UTC, beng9re commented on src/test/java/lotto/domain/LastWeekLottoValidatorTest.java
> +}
앗.. 파일끝에 공백이

2024-05-11 12:18 UTC, beng9re commented on src/main/java/lotto/domain/LastWeekLottoValidator.java
> +    public static final int MIN_LOTTO_NUMBER = 1;
LastWeekLottoValidator의 상수로 `MIN_LOTTO_NUMBER`가지고 있고 
LottoGenrator의 상수로도 MIN_LOTTO_NUMBER을 가지고 있던데 
관심사가 다르니 다르게 관리한 의도라면 해당 부분에서만 필요하다면 private로 선언해주는게 좋을꺼 같고 
같은 의미라면 한곳에서 관리를 하고 pulblic으로 열어두는게 좋아보입니다!

2024-05-11 12:18 UTC, beng9re commented on src/main/java/lotto/domain/LastWeekLottoValidator.java
> +            throw new IllegalArgumentException("당첨번호는 콤마로 구분된 숫자 6개이어야 합니다.");
사소로운거지만 문구도 상수를 활용하면 좋을꺼 같아요 : )

2024-05-11 12:18 UTC, beng9re commented on src/main/java/lotto/domain/LottoCalculator.java
> +public class LottoCalculator {
로또 계산을 위한 클래스군요 좋습니다!

2024-05-11 12:18 UTC, beng9re commented on src/main/java/lotto/LottoApplication.java
> +        LottoApplication lottoApplication = new LottoApplication(new LottoConsumer(), new InputView(), new OutputView());
로또 어플리케이션이 수행되려면 컨슈머와, 뷰들이 필요하군요 
서비스도 같이 의존 받을수 있을꺼 같아요!

2024-05-14 00:09 UTC, babysean commented on src/main/java/lotto/service/LottoService.java
> +        return new LottoTicket(numberList);
LottoTicket이 자동 로또번호와 지난주 로또번호를 둘다 관리해요 !
생성자 2개를 만들어서 관리해볼게요 !

<img width="679" alt="image" src="https://github.com/Doolki/java-lotto/assets/26477789/7db3aa0f-3cf3-4a39-80c7-abb0f33f10dc">

2024-05-14 00:33 UTC, babysean commented on src/main/java/lotto/service/LottoService.java
> +        return Math.floor(rateOfReturn * 1000) / 1000;
수익률 계산 메서드도 LottoCalculator 로 옮길게요 !

2024-05-14 00:39 UTC, babysean commented on src/main/java/lotto/service/LottoService.java
> +        LottoCalculator calculator = new LottoCalculator();
LottoService의 생성자에 LottoCalculator의 의존성을 주입하여 사용하는 것으로 리팩토링할게요 👍🏼

2024-05-14 00:49 UTC, babysean commented on src/main/java/lotto/view/InputView.java
> +    public static final int LOTTO_PRICE = 1000;
오타가 있었네요 😢 
LottoTicket 클래스에 모아볼게요 !

2024-05-14 00:50 UTC, babysean commented on src/main/java/lotto/LottoApplication.java
> +    private final LottoConsumer consumer;
제가 놓치는 부분도 IntelliJ가 하나하나 잡아주니 좋아요

2024-05-14 00:54 UTC, babysean commented on src/test/java/lotto/domain/LastWeekLottoValidatorTest.java
> +}
😮 추가할게요 !

2024-05-14 00:57 UTC, babysean commented on src/main/java/lotto/LottoApplication.java
> +        LottoApplication lottoApplication = new LottoApplication(new LottoConsumer(), new InputView(), new OutputView());
<img width="1117" alt="image" src="https://github.com/Doolki/java-lotto/assets/26477789/d95af160-59a6-49c1-a1f4-588e6694b2fa">

LottoApplication 이 이렇게 더러워지는데 이게 맞을까요 ??

2024-05-14 01:14 UTC, babysean commented on src/main/java/lotto/domain/LastWeekLottoValidator.java
> +            throw new IllegalArgumentException("당첨번호는 콤마로 구분된 숫자 6개이어야 합니다.");
상수로 사용해볼게요 !

2024-05-14 01:16 UTC, babysean commented on src/main/java/lotto/domain/LastWeekLottoValidator.java
> +    public static final int MIN_LOTTO_NUMBER = 1;
로또 번호의 범위이기에 같은 관심사의 상수에요 !

LottoTicket에서 선언되는 것이 적절해 보이니 옮겨볼게요 !

2024-05-14 01:20 UTC, babysean commented
리뷰 부탁 드립니다 🙏🏼

2024-05-14 10:29 UTC, beng9re commented
test

2024-05-14 10:34 UTC, beng9re commented
temp

2024-05-14 11:09 UTC, beng9re requested changes
수고 많으셨습니다. 피드백 반영 잘 해주셨습니다.

당장 머지해도 되지만 
코멘트 확인해주시구 수정하실꺼 있으시면 수정하시고 코멘트 답변 확인하고 
머지 할지 검토해보겠습니다!

> LottoApplication 이 이렇게 더러워지는데 이게 맞을까요 ??

통상적으로 로또 컨슈머는 단한명이 아닌 여러명이 될 수도 있을꺼 같아서 
LottoApplication 클래스에서 LottoConsumer가 과연 필드로 가지고 있는게 맞을까? 라는 생각을 한번 해보시구! 파라미터가 많은 부분은 팩토리 패턴을 적용해보시면 좋을꺼 같아요

2024-05-14 11:09 UTC, beng9re commented on src/main/java/lotto/domain/LottoTicket.java
> +        this.numbers = Arrays.stream(numbers).map(Integer::parseInt).collect(Collectors.toList());
```suggestion
this(Arrays.stream(numbers)
      .map(Integer::parseInt)
      .collect(Collectors.toList());
```
이제 String[] 타입으로도 로또티켓을 만들수 있군요
다음과 같이 작성하면 주생성자에서 관리가 가능하답니다.

2024-05-14 11:09 UTC, beng9re commented on src/main/java/lotto/service/LottoService.java
> +     * 지난 주 당첨 로또를 가공하여 LottoTicket 으로 만듭니다.
오타수정 좋습니다!

2024-05-14 11:09 UTC, beng9re commented on src/main/java/lotto/domain/LottoCalculator.java
> +    public Double getProfit(int prizeMoney, int money) {
메서드 위치가 변경되서 계산 역할에 수익율까지 계산할수 있군요 좋습니다 👍

2024-05-14 11:09 UTC, beng9re commented on src/main/java/lotto/domain/LottoCalculator.java
> +    public Double getProfit(int prizeMoney, int money) {
Double을 기본타입으로 쓰지 않은 이유가 있을까요?

2024-05-14 11:09 UTC, beng9re commented on src/main/java/lotto/domain/LottoConsumer.java
> +public class LottoConsumer {
제가 생각하기에 LottoConsumer는 
로또티겟에 대한 상태를 가지고 있을꺼 같은 클래스인데 
상태를 관리를 안하게 된 이유가 있을까요:?

2024-05-15 23:21 UTC, babysean commented on src/main/java/lotto/domain/LottoTicket.java
> +        this.numbers = Arrays.stream(numbers).map(Integer::parseInt).collect(Collectors.toList());
아 지난번에 알려주신게 이거군요 ! `생성자 this` 를 활용해볼게요 !

2024-05-15 23:27 UTC, babysean commented on src/main/java/lotto/domain/LottoCalculator.java
> +    public Double getProfit(int prizeMoney, int money) {
습관적으로 참조타입으로 사용해요 ㅠㅠ 기본타입으로 변경 할게요 !

2024-05-15 23:39 UTC, babysean commented on src/main/java/lotto/domain/LottoConsumer.java
> +public class LottoConsumer {
저는 구매자가 1명일 때만을 가정하여 코딩하였기에 이렇게 소스가 짜진 것 같아요 !

여러 구매자가 있다고 가정하고 다시 한 번 리팩토링 해볼게요

2024-05-16 05:17 UTC, babysean commented
LottoConsumer 를 메서드안에 지역변수로 변경하였고 LottoApplication 도 팩토리 패턴으로 개선해봤어요.

리뷰 부탁 드려요 🙏🏼

2024-05-17 01:23 UTC, beng9re approved these changes
잘 반영해주셨습니다! 
이번 단계는 이만 머지 하겠습니다!

코멘트 남겨두었으니 확인 해보세요!

2024-05-17 01:23 UTC, beng9re commented on src/main/java/lotto/domain/LottoTicket.java
> +        this(Arrays.stream(numbers)
피드백 반영 👍

2024-05-17 01:23 UTC, beng9re commented on src/main/java/lotto/factory/LottoApplicationFactory.java
> +    public LottoApplication createLottoApplication() {
팩토리 패턴 좋습니다! 
이제 생성에 대한 로직을 모을수 있겠군요.
다른 유형의 LottoApplication이 생긴다면 해당 부분에 작성하면 되겠네요 

개인적으로 팩토리 메서드는 static으로 작성하는 편입니다. 
LottoApplicationFactory클래스를 인스턴스 할 필요가 없다고 생각이 되어서요

2024-05-17 01:25 UTC, merged

2024-05-17 06:25 UTC, babysean commented on src/main/java/lotto/factory/LottoApplicationFactory.java
> +    public LottoApplication createLottoApplication() {
다음번 팩토리 패턴을 사용할 때는 static을 사용할게요 !